import type { ServiceConfig } from '@/types'

export const SERVICE_CATALOG: ServiceConfig[] = [
  {
    id: 'roofing',
    name: 'Roofing',
    badge: 'MOST POPULAR',
    badgeColor: 'bg-amber-500 text-white',
    tagline: 'Protect your home with premium roofing solutions',
    description: 'Complete residential roofing services — from full replacement to repairs and inspections.',
    features: ['Hurricane-Rated', 'Energy Efficient', '25-Year Warranty'],
    stat: { label: 'Projects Completed', value: '2,847' },
    optionGroups: [
      {
        id: 'material',
        label: 'Roofing Material',
        required: true,
        type: 'single',
        options: [
          { id: 'shingle', label: 'Architectural Shingle', description: 'Most affordable, 25-30 year lifespan' },
          { id: 'barrel_tile', label: 'Barrel Tile', description: 'Classic Florida look, 50+ year lifespan' },
          { id: 'metal', label: 'Standing Seam Metal', description: 'Maximum durability, 50+ years' },
          { id: 'terracotta', label: 'Terracotta Clay', description: 'Premium Mediterranean style' },
        ],
      },
      {
        id: 'service_type',
        label: 'Service Type',
        required: true,
        type: 'single',
        options: [
          { id: 'replace', label: 'Full Replacement' },
          { id: 'repair', label: 'Repair' },
          { id: 'inspection', label: 'Inspection Only' },
        ],
      },
      {
        id: 'addons',
        label: 'Add-Ons',
        required: false,
        type: 'multi',
        options: [
          { id: 'gutters', label: 'Gutter Installation' },
          { id: 'insulation', label: 'Attic Insulation' },
          { id: 'solar_prep', label: 'Solar Panel Prep' },
        ],
      },
    ],
  },
  {
    id: 'windows_doors',
    name: 'Impact Windows & Doors',
    badge: 'CODE REQUIRED',
    badgeColor: 'bg-destructive text-destructive-foreground',
    tagline: 'Hurricane protection with energy-saving impact glass',
    description: 'Florida building code compliant impact windows and doors for maximum protection.',
    features: ['Impact-Rated', 'UV Protection', 'Noise Reduction'],
    stat: { label: 'Windows Installed', value: '18,420' },
    optionGroups: [
      {
        id: 'glass_type',
        label: 'Glass Type',
        required: true,
        type: 'single',
        options: [
          { id: 'standard', label: 'Standard Impact' },
          { id: 'impact_plus', label: 'Impact + Solar Control' },
        ],
      },
      {
        id: 'products',
        label: 'Product Types',
        required: true,
        type: 'multi',
        options: [
          { id: 'single_hung', label: 'Single-Hung Windows' },
          { id: 'casement', label: 'Casement Windows' },
          { id: 'sliding', label: 'Sliding Glass Doors' },
          { id: 'french', label: 'French Doors' },
          { id: 'entry', label: 'Entry Doors' },
        ],
      },
      {
        id: 'scope',
        label: 'Scope',
        required: true,
        type: 'single',
        options: [
          { id: 'full', label: 'Full Home' },
          { id: 'partial', label: 'Partial (Select Rooms)' },
          { id: 'single', label: 'Single Window/Door' },
        ],
      },
    ],
  },
  {
    id: 'pool',
    name: 'Pool & Oasis',
    tagline: 'Your backyard paradise, designed and built',
    description: 'Custom pool design and construction with premium finishes and water features.',
    features: ['Custom Design', 'Smart Controls', 'Eco-Friendly'],
    stat: { label: 'Pools Built', value: '1,203' },
    optionGroups: [
      {
        id: 'model',
        label: 'Pool Model',
        required: true,
        type: 'single',
        options: [
          { id: '12x24', label: '12×24 Classic' },
          { id: '14x28', label: '14×28 Freeform' },
          { id: '16x32', label: '16×32 Resort' },
        ],
      },
      {
        id: 'paver',
        label: 'Paver Finish',
        required: true,
        type: 'single',
        options: [
          { id: 'travertine', label: 'Travertine' },
          { id: 'marble', label: 'Marble' },
          { id: 'concrete', label: 'Stamped Concrete' },
          { id: 'slate', label: 'Natural Slate' },
        ],
      },
      {
        id: 'addons',
        label: 'Add-Ons',
        required: false,
        type: 'multi',
        options: [
          { id: 'spa', label: 'Attached Spa' },
          { id: 'waterfall', label: 'Waterfall Feature' },
          { id: 'led', label: 'LED Lighting' },
          { id: 'heater', label: 'Pool Heater' },
        ],
      },
    ],
  },
  {
    id: 'driveways',
    name: 'Driveways',
    tagline: 'Make a lasting first impression',
    description: 'Premium driveway installation and resurfacing for curb appeal that lasts.',
    features: ['Weather-Proof', 'Low Maintenance', 'Custom Patterns'],
    stat: { label: 'Driveways Paved', value: '956' },
    optionGroups: [
      {
        id: 'surface',
        label: 'Surface Material',
        required: true,
        type: 'single',
        options: [
          { id: 'pavers', label: 'Interlocking Pavers' },
          { id: 'stamped', label: 'Stamped Concrete' },
          { id: 'asphalt', label: 'Asphalt' },
          { id: 'stone', label: 'Natural Stone' },
        ],
      },
      {
        id: 'scope',
        label: 'Scope',
        required: true,
        type: 'single',
        options: [
          { id: 'full', label: 'Full Driveway' },
          { id: 'overlay', label: 'Overlay' },
          { id: 'repair', label: 'Repair Only' },
        ],
      },
      {
        id: 'addons',
        label: 'Add-Ons',
        required: false,
        type: 'multi',
        options: [
          { id: 'border', label: 'Decorative Border' },
          { id: 'lighting', label: 'Driveway Lighting' },
          { id: 'drainage', label: 'Drainage System' },
        ],
      },
    ],
  },
  {
    id: 'pergolas',
    name: 'Pergolas & Terraces',
    badge: 'TRENDING',
    badgeColor: 'bg-success text-success-foreground',
    tagline: 'Extend your living space outdoors',
    description: 'Custom outdoor structures for shade, style, and year-round entertainment.',
    features: ['Weather-Resistant', 'Motorized Options', 'Custom Sizes'],
    stat: { label: 'Structures Built', value: '734' },
    optionGroups: [
      {
        id: 'structure',
        label: 'Structure Type',
        required: true,
        type: 'single',
        options: [
          { id: 'aluminum', label: 'Aluminum Pergola' },
          { id: 'wood', label: 'Wood Beam Pergola' },
          { id: 'louvered', label: 'Louvered Roof' },
        ],
      },
      {
        id: 'size',
        label: 'Size',
        required: true,
        type: 'single',
        options: [
          { id: '10x12', label: '10×12 ft' },
          { id: '12x16', label: '12×16 ft' },
          { id: 'custom', label: 'Custom Size' },
        ],
      },
      {
        id: 'addons',
        label: 'Add-Ons',
        required: false,
        type: 'multi',
        options: [
          { id: 'fans', label: 'Ceiling Fans' },
          { id: 'kitchen', label: 'Outdoor Kitchen' },
          { id: 'deck', label: 'Composite Deck' },
          { id: 'screen', label: 'Screen Enclosure' },
        ],
      },
    ],
  },
  {
    id: 'air_conditioning',
    name: 'Air Conditioning',
    badge: 'ESSENTIAL',
    badgeColor: 'bg-primary text-primary-foreground',
    tagline: 'Stay cool with efficient climate control',
    description: 'HVAC installation, replacement, and maintenance for South Florida homes.',
    features: ['Energy Star', 'Smart Thermostat', '10-Year Warranty'],
    stat: { label: 'Systems Installed', value: '4,312' },
    optionGroups: [
      {
        id: 'system',
        label: 'System Type',
        required: true,
        type: 'single',
        options: [
          { id: 'central_2', label: 'Central AC — 2 Ton' },
          { id: 'central_3', label: 'Central AC — 3 Ton' },
          { id: 'central_4', label: 'Central AC — 4 Ton' },
          { id: 'mini_single', label: 'Mini-Split — Single Zone' },
          { id: 'mini_multi', label: 'Mini-Split — Multi Zone' },
        ],
      },
      {
        id: 'addons',
        label: 'Add-Ons',
        required: false,
        type: 'multi',
        options: [
          { id: 'thermostat', label: 'Smart Thermostat' },
          { id: 'ducts', label: 'Duct Cleaning/Replacement' },
          { id: 'purifier', label: 'Air Purifier' },
          { id: 'maintenance', label: 'Annual Maintenance Plan' },
        ],
      },
    ],
  },
  {
    id: 'kitchen',
    name: 'Kitchen Remodel',
    badge: 'PHASE 2',
    badgeColor: 'bg-muted text-muted-foreground',
    tagline: 'Transform your kitchen into the heart of your home',
    description: 'Full kitchen renovations from cabinets to countertops to appliances.',
    features: ['Custom Cabinets', 'Quartz Counters', 'Smart Appliances'],
    stat: { label: 'Kitchens Remodeled', value: '—' },
    phase2: true,
    optionGroups: [],
  },
  {
    id: 'bathroom',
    name: 'Bathroom Remodel',
    badge: 'PHASE 2',
    badgeColor: 'bg-muted text-muted-foreground',
    tagline: 'Create your personal spa retreat',
    description: 'Modern bathroom renovations with premium fixtures and finishes.',
    features: ['Walk-In Shower', 'Heated Floors', 'Smart Fixtures'],
    stat: { label: 'Bathrooms Remodeled', value: '—' },
    phase2: true,
    optionGroups: [],
  },
  {
    id: 'wall_paneling',
    name: 'Wall Paneling & Design',
    badge: 'NEW',
    badgeColor: 'bg-primary text-primary-foreground',
    tagline: 'Elevate your interiors with designer wall treatments',
    description: 'Custom wall paneling, accent walls, and interior design treatments.',
    features: ['Designer Styles', 'Quick Install', 'Eco Materials'],
    stat: { label: 'Walls Designed', value: '412' },
    optionGroups: [
      {
        id: 'style',
        label: 'Panel Style',
        required: true,
        type: 'single',
        options: [
          { id: 'shiplap', label: 'Shiplap' },
          { id: 'board_batten', label: 'Board & Batten' },
          { id: '3d', label: '3D Panels' },
          { id: 'wainscoting', label: 'Wainscoting' },
        ],
      },
      {
        id: 'rooms',
        label: 'Rooms',
        required: true,
        type: 'multi',
        options: [
          { id: 'living', label: 'Living Room' },
          { id: 'bedroom', label: 'Bedroom' },
          { id: 'dining', label: 'Dining Room' },
          { id: 'entryway', label: 'Entryway' },
          { id: 'office', label: 'Home Office' },
        ],
      },
    ],
  },
  {
    id: 'garage',
    name: 'Garage Addition',
    tagline: 'Add value with a custom garage build',
    description: 'New garage construction with smart storage and premium finishes.',
    features: ['Smart Door', 'Epoxy Floors', 'Climate Control'],
    stat: { label: 'Garages Built', value: '287' },
    optionGroups: [
      {
        id: 'size',
        label: 'Garage Size',
        required: true,
        type: 'single',
        options: [
          { id: 'single', label: 'Single Bay (12×20)' },
          { id: 'double', label: 'Double Bay (22×22)' },
        ],
      },
      {
        id: 'addons',
        label: 'Add-Ons',
        required: false,
        type: 'multi',
        options: [
          { id: 'smart_door', label: 'Smart Garage Door' },
          { id: 'epoxy', label: 'Epoxy Floor Coating' },
          { id: 'loft', label: 'Storage Loft' },
          { id: 'workshop', label: 'Workshop Setup' },
        ],
      },
    ],
  },
]

export const LEAD_STATUS_CONFIG: Record<string, { label: string; color: string; icon: string }> = {
  pending: { label: 'Pending', color: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400', icon: '⏳' },
  confirmed: { label: 'Confirmed', color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400', icon: '✅' },
  rejected: { label: 'Rejected', color: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400', icon: '🚫' },
  rescheduled: { label: 'Rescheduled', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400', icon: '🔄' },
  completed: { label: 'Completed', color: 'bg-slate-100 text-slate-800 dark:bg-slate-900/30 dark:text-slate-400', icon: '☑️' },
}
