// AUTO-GENERATED by scripts/seed-vendor-prices.mjs — do NOT edit by hand.
// Maps mock-vendor-id (from MOCK_VENDORS in mock-data.ts) to the real
// Supabase auth.users/profiles UUID so the FE can join mock display data
// (name, rating, avatar) to real-DB vendor_option_prices rows.

export const DEMO_VENDOR_UUID_BY_MOCK_ID: Record<string, string> = {
  "v-1": "fc0d8ff3-cc1c-4101-a4b3-068594753bbf",
  "v-2": "4c3f13c3-4647-48af-864d-ecbbb92a47f9",
  "v-3": "9d9c6608-8ef3-4502-a1f3-12f29dea1ca1"
}
