// create-rep-request edge fn — homeowner self-submit path.
//
// FLOW (per kratos durability rule — insert-pending-payment-first, then charge,
// then webhook-flip):
//   1. Authenticate homeowner from JWT; reject non-homeowner roles.
//   2. Validate payload shape (address + contact_phone + requested_visit_times
//      + at least one visit-window bucket).
//   3. Derive service_tz from address.state via STATE_TO_TZ; expand each
//      bucket+date into a canonical UTC window via bucketToWindow().
//   4. INSERT rep_requests row with status=pending_payment, stripe_idempotency_key
//      auto-generated by DB DEFAULT. Capture id.
//   5. APPEND rep_request_events row event_type=created (actor_id=homeowner,
//      actor_role=homeowner, payload={address.zip, source: 'homeowner_self'}).
//   6. Stripe PaymentIntent.create with amount=25000, currency=usd, customer
//      lookup-or-create, metadata={rep_request_id, homeowner_id},
//      idempotencyKey=stripe_idempotency_key.
//   7. UPDATE rep_requests set stripe_payment_intent_id=pi.id.
//   8. APPEND event_type=charge_attempted (system actor=NULL; payload={pi_id,
//      idempotency_key, amount_cents}).
//   9. Return { rep_request_id, client_secret } — FE confirms with Stripe.js;
//      charge.succeeded webhook flips status to 'new'.
//
// FAILURE MODES:
//   - INSERT fails (RLS / role validation trigger / CHECK violation): return
//     400 with the underlying error. No money moved, no orphan rows.
//   - Stripe PI.create fails after DB INSERT: rep_requests row stays in
//     pending_payment with stripe_payment_intent_id=NULL. Admin sweep
//     (see migration 101 design notes) DELETEs these safely after a TTL.
//   - PaymentIntent succeeds but UPDATE of stripe_payment_intent_id fails:
//     idempotency_key guarantees the next retry reaches the same PI; no
//     duplicate charges. The webhook can still match via metadata.rep_request_id.

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import Stripe from 'https://esm.sh/stripe@17.7.0?target=deno'
import {
  CORS_HEADERS,
  STATE_TO_TZ,
  VISIT_FEE_CENTS,
  bucketToWindow,
  type VisitWindowBucket,
} from '../_shared/rep-request/index.ts'

interface CreateRepRequestPayload {
  address: {
    line1: string
    line2?: string | null
    city: string
    state: string // 2-letter; keyed into STATE_TO_TZ
    zip: string
  }
  contact_phone: string
  visit_window_picks: Array<{
    bucket: VisitWindowBucket
    iso_date: string // YYYY-MM-DD in homeowner's local frame; service_tz overlay applied
  }>
  description?: string
  access_notes?: string
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS_HEADERS })
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'method_not_allowed' }), {
      status: 405,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  const anonKey = Deno.env.get('SUPABASE_ANON_KEY')!
  const stripeKey = Deno.env.get('STRIPE_SECRET_KEY') || ''

  if (!stripeKey) {
    return new Response(JSON.stringify({ error: 'stripe_not_configured' }), {
      status: 503,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  // Authenticate the homeowner via the JWT in Authorization header.
  const authHeader = req.headers.get('Authorization') || ''
  const jwt = authHeader.replace(/^Bearer\s+/i, '')
  if (!jwt) {
    return new Response(JSON.stringify({ error: 'unauthorized' }), {
      status: 401,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const userClient = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
  })
  const { data: userData, error: userErr } = await userClient.auth.getUser()
  if (userErr || !userData?.user) {
    return new Response(JSON.stringify({ error: 'unauthorized' }), {
      status: 401,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }
  const homeownerId = userData.user.id

  // service-role client for the DB writes — RLS would allow the INSERT via
  // the homeowner_create policy, but the event-log INSERT needs service-role
  // (no client INSERT policy on rep_request_events).
  const admin = createClient(supabaseUrl, serviceKey)

  // Role check — only homeowners can self-submit.
  const { data: profile, error: profileErr } = await admin
    .from('profiles')
    .select('id, role')
    .eq('id', homeownerId)
    .maybeSingle()
  if (profileErr || !profile) {
    return new Response(JSON.stringify({ error: 'profile_not_found' }), {
      status: 403,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }
  if (profile.role !== 'homeowner') {
    return new Response(JSON.stringify({ error: 'forbidden_role', detail: 'homeowners only — admins use create-rep-request-on-behalf' }), {
      status: 403,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  let payload: CreateRepRequestPayload
  try {
    payload = await req.json()
  } catch {
    return new Response(JSON.stringify({ error: 'invalid_json' }), {
      status: 400,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  // Validate payload shape (minimal — full validation deferred to FE + DB
  // CHECKs; here we catch the structural failures cheaply).
  const { address, contact_phone, visit_window_picks } = payload
  if (
    !address || !address.line1 || !address.city || !address.state || !address.zip ||
    !contact_phone ||
    !Array.isArray(visit_window_picks) || visit_window_picks.length === 0
  ) {
    return new Response(JSON.stringify({ error: 'invalid_payload' }), {
      status: 400,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const serviceTz = STATE_TO_TZ[address.state.toUpperCase()]
  if (!serviceTz) {
    return new Response(JSON.stringify({ error: 'unsupported_state', detail: `no service timezone for state=${address.state}` }), {
      status: 400,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  // Expand the categorical picks into canonical VisitWindow rows.
  const requestedWindows = []
  for (const pick of visit_window_picks) {
    const window = bucketToWindow(pick.bucket, pick.iso_date, serviceTz)
    if (!window) {
      return new Response(JSON.stringify({ error: 'invalid_visit_window', detail: `bucket=${pick.bucket} date=${pick.iso_date} does not match the bucket's allowed day-of-week` }), {
        status: 400,
        headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
      })
    }
    requestedWindows.push({
      window_start_utc: window.window_start_utc,
      window_end_utc: window.window_end_utc,
      service_tz: serviceTz,
      bucket_label: pick.bucket,
    })
  }

  // INSERT rep_requests row (status=pending_payment, stripe_idempotency_key
  // auto-filled by DB DEFAULT gen_random_uuid).
  const { data: inserted, error: insertErr } = await admin
    .from('rep_requests')
    .insert({
      homeowner_id: homeownerId,
      created_by: homeownerId,
      address,
      contact_phone,
      requested_visit_times: requestedWindows,
      description: payload.description ?? null,
      access_notes: payload.access_notes ?? null,
      status: 'pending_payment',
      charge_status: 'not_charged',
    })
    .select('id, stripe_idempotency_key')
    .single()

  if (insertErr || !inserted) {
    console.error('rep_requests insert failed', insertErr?.message)
    return new Response(JSON.stringify({ error: 'insert_failed', detail: insertErr?.message }), {
      status: 500,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  const repRequestId = inserted.id as string
  const idempotencyKey = inserted.stripe_idempotency_key as string

  await admin.from('rep_request_events').insert({
    rep_request_id: repRequestId,
    actor_id: homeownerId,
    actor_role: 'homeowner',
    event_type: 'created',
    payload: { source: 'homeowner_self', address_zip: address.zip },
  })

  // Stripe PaymentIntent.create with idempotency key (uuid-stable, replay-safe).
  const stripe = new Stripe(stripeKey, { apiVersion: '2024-06-20' })

  let pi: Stripe.PaymentIntent
  try {
    pi = await stripe.paymentIntents.create(
      {
        amount: VISIT_FEE_CENTS,
        currency: 'usd',
        capture_method: 'automatic',
        description: 'BuildConnect Concierge — Rep Visit',
        metadata: {
          rep_request_id: repRequestId,
          homeowner_id: homeownerId,
        },
        automatic_payment_methods: { enabled: true },
      },
      { idempotencyKey }
    )
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    console.error('stripe paymentIntents.create failed', msg)
    // Row stays in pending_payment with stripe_payment_intent_id=NULL.
    // Admin sweep cleans up after TTL. No money moved.
    await admin.from('rep_request_events').insert({
      rep_request_id: repRequestId,
      event_type: 'charge_failed',
      payload: { stripe_error: msg, stage: 'paymentIntents.create' },
    })
    return new Response(JSON.stringify({ error: 'stripe_create_failed', detail: msg }), {
      status: 502,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    })
  }

  await admin
    .from('rep_requests')
    .update({ stripe_payment_intent_id: pi.id })
    .eq('id', repRequestId)

  await admin.from('rep_request_events').insert({
    rep_request_id: repRequestId,
    event_type: 'charge_attempted',
    payload: {
      stripe_payment_intent_id: pi.id,
      idempotency_key: idempotencyKey,
      amount_cents: VISIT_FEE_CENTS,
    },
  })

  return new Response(
    JSON.stringify({
      rep_request_id: repRequestId,
      client_secret: pi.client_secret,
      amount_cents: VISIT_FEE_CENTS,
    }),
    { headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } }
  )
})
