-- 093_homeowner_documents_insert_system_project_report.sql
-- Scoped RLS INSERT policy on public.homeowner_documents admitting the
-- Mark-as-Sold project_report row written by src/lib/project-report-on-sold.ts.
--
-- task_arc — kratos msg 1781652331925-kratos-fngtn / apollo live-fire on
-- preview a46c1138. The Mark-as-Sold trigger generates the customer-copy
-- project_report PDF (showMargin=false, never persisted with margin) and
-- inserts a homeowner_documents row with uploaded_by='system'. Storage
-- upload landed 200, but the row INSERT 403'd with "new row violates
-- row-level security policy for table homeowner_documents" and the store's
-- compensating cleanup then DELETE'd the just-uploaded storage object.
-- Net: zero honest project_report rows ever persisted.
--
-- ROOT CAUSE: the existing INSERT policy set on public.homeowner_documents
-- admits:
--   "Homeowners insert own documents"            WITH CHECK (homeowner_id = auth.uid())
--   "Vendors INSERT documents on assigned projects"
--      WITH CHECK (uploaded_by = 'vendor' AND vendor_id = auth.uid() AND
--                  EXISTS (sent_projects WHERE id = sent_project_id AND vendor_id = auth.uid()))
--   "Admins manage all homeowner documents"      (admin role)
-- None of those admit uploaded_by='system'. The trigger runs under the
-- VENDOR's JWT (fire-and-forget after markProjectSold + the contract
-- upload in lead-workflow.tsx), so vendor-INSERT was the only path with
-- any chance of matching — and it explicitly requires uploaded_by='vendor',
-- which would lie about provenance and break the "Generated by BuildConnect"
-- system-uploader chip downstream (banked: chip resolves orphan-doc
-- confusion exactly because uploaded_by='system' is honest).
--
-- FIX: a NEW, tightly-scoped INSERT policy that admits exactly the trigger's
-- write shape and nothing else. The vendor JWT is still the auth context
-- because the trigger runs in the vendor's session; the policy ties the
-- write to a sold sent_project that vendor owns. Honest provenance stays
-- 'system'; the chip and audit trail remain truthful.
--
-- PREDICATE:
--   uploaded_by = 'system'
--   AND doc_type = 'project_report'
--   AND EXISTS (
--     SELECT 1 FROM sent_projects sp
--     WHERE sp.id = sent_project_id
--       AND sp.vendor_id = auth.uid()
--       AND sp.status = 'sold'
--   )
--
-- Why these clauses:
--   uploaded_by = 'system'   pins this policy to system-provenance writes
--                            only — does not loosen the vendor or homeowner
--                            insert paths, which keep their original gates.
--   doc_type = 'project_report'
--                            scopes the policy to the single doc_type the
--                            Mark-as-Sold trigger writes. A future system-
--                            generated doc_type would need its own policy
--                            review (intentional friction; no broad
--                            "any system doc" admit).
--   sp.id = sent_project_id  ties the row to a real sent_project row.
--   sp.vendor_id = auth.uid()
--                            the vendor whose JWT is firing the INSERT must
--                            own the underlying sent_project — a vendor
--                            cannot land a system project_report on someone
--                            else's lead.
--   sp.status = 'sold'       the trigger fires only on Mark-as-Sold, so the
--                            sp must already be 'sold' when the INSERT runs.
--                            This is a tight invariant match — anything not
--                            sold can't legitimately produce a project_report.
--
-- This is technically a LOOSENING (the table accepts a new shape it didn't
-- before), but zero honest traffic was ever accepted under the prior set
-- (the trigger always 403'd). After deploy, apollo re-runs the full live-
-- fire walk to confirm the real trigger now lands the row (producer-side
-- verify, not a hand-built probe). Banked rule:
-- feedback_tightening_fix_verify_client_still_produces_accepted_shape
-- (here in reverse — a loosening fix, real-client re-verify after).
--
-- RLS-only: zero FE bytes changed. Bundle stays byte-identical to e4daed9
-- (index-CcLcqz8M.js / md5 a9f0da9fc51270bcf35f19b350eb2b89 / 3472783).

BEGIN;

DROP POLICY IF EXISTS "System INSERT project_report on sold sent_projects" ON public.homeowner_documents;

CREATE POLICY "System INSERT project_report on sold sent_projects"
  ON public.homeowner_documents
  FOR INSERT
  TO authenticated
  WITH CHECK (
    uploaded_by = 'system'
    AND doc_type = 'project_report'
    AND EXISTS (
      SELECT 1 FROM public.sent_projects sp
      WHERE sp.id = sent_project_id
        AND sp.vendor_id = auth.uid()
        AND sp.status = 'sold'
    )
  );

COMMIT;
