-- 094_homeowner_documents_doc_type_project_report.sql
-- Widen public.homeowner_documents.doc_type CHECK to include 'project_report'.
--
-- task_arc — kratos msg 1781652668247-kratos-iky7r / apollo round-2 live-fire.
-- Migration 093 cleared the RLS gate on the Mark-as-Sold trigger insert
-- (uploaded_by='system' now admitted), but the FE then hit a 400 from
-- pg_constraint:
--   new row for relation "homeowner_documents" violates check constraint
--   "homeowner_documents_doc_type_check"
-- Live pg_constraint definition admitted:
--   license / permit / association_permit / sketch / measurement /
--   agreement / contract / quote / photo / other
-- 'project_report' was absent — same incomplete cb645c5 ship that omitted
-- the RLS policy also omitted the substrate-level enum widen.
--
-- FIX: drop + re-add the CHECK with project_report added to the array.
-- Position matches the FE DOC_TYPE_ORDER (after contract, before quote) —
-- not load-bearing for the constraint itself, but keeps the substrate enum
-- in lockstep with src/lib/homeowner-doc-display.tsx ordering for any
-- future readability check. The NULL-allow leg is preserved so existing
-- legacy rows with doc_type=NULL stay valid.
--
-- SUBSTRATE SWEEP (kratos directive — confirm no third gap):
--   constraints — only the doc_type CHECK rejected the trigger shape;
--                 category_check admits 'other' (trigger uses 'other');
--                 uploaded_by_check admits 'system' (trigger uses 'system');
--                 PK/FKs (homeowner_id → profiles, sent_project_id →
--                 sent_projects, vendor_id → profiles) admit the trigger
--                 values (homeowner_id from sp.homeowner_id, sent_project_id
--                 = sp.id, vendor_id from sp.vendor_id ?? sp.contractor?.
--                 vendor_id ?? null — nullable column accepts null).
--   columns    — NOT NULL set covers id (default), homeowner_id (set),
--                 category (set='other'), filename (set), storage_path
--                 (set by store), created_at (default), uploaded_by
--                 (set='system'). All others nullable.
--   triggers   — none user-defined on homeowner_documents (only internal
--                 RLS enforcement).
--   RLS policies — after 093, INSERT path admits the system+project_report
--                 shape; SELECT path admits homeowner (own) + vendor (own
--                 vendor_id OR own sp.vendor_id, second leg covers when
--                 the trigger writes vendor_id=null) + admin.
-- No third substrate gap surfaced — apollo's re-run after 094 should land
-- the row, surface it on /home/documents (homeowner SELECT own) and
-- /vendor/homeowners/:homeownerId (vendor sp-side SELECT), with the
-- "Generated by BuildConnect" chip and the admin-margin button respecting
-- the role + platform-toggle gates.
--
-- RLS-only / CHECK-only — zero FE bytes changed. Bundle stays byte-
-- identical to e4daed9 (index-CcLcqz8M.js / md5 a9f0da9fc51270bcf35f19b
-- 350eb2b89 / 3472783).

BEGIN;

ALTER TABLE public.homeowner_documents
  DROP CONSTRAINT IF EXISTS homeowner_documents_doc_type_check;

ALTER TABLE public.homeowner_documents
  ADD CONSTRAINT homeowner_documents_doc_type_check
  CHECK (
    doc_type IS NULL
    OR doc_type = ANY (ARRAY[
      'license',
      'permit',
      'association_permit',
      'sketch',
      'measurement',
      'agreement',
      'contract',
      'project_report',
      'quote',
      'photo',
      'other'
    ])
  );

COMMIT;
